---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      version: ^5.0.0
  interval: 15m0s
  values:
    provider: digitalocean
    domainFilters:
      - wks.kingdonb.dev
    source: ingress
  valuesFrom:
  - kind: Secret
    name: external-dns-do-token
    valuesKey: do_token
    targetPath: digitalocean.apiToken
    optional: false
